### ISSUE TITLE
Unicode characters on nicknames causes failures on login process

### ISSUE THREAD

**Issue by DaniellMesquita** [Ecuacion/Pokemon-Showdown-Node-Bot#29]
I have an bot called 'Espelho Bobágico", and the "Á" isn't rechognized.

**Comment by Ecuacion** [comment]
Fixed in 6c5c0ec09829be5ccb63d2d2ccee8090e5877c8d

Note: If it does not work, try changing the charset of your `config.js` to UTF-8 or replacing the Unicode characters with the corresponding escape sequence `"\uXXXX"`

Note2: If you are trying it on main server, there is a filter for nicknames so you can't use some unicode ranges (for example letters with accents). This is intended to avoid impersonation and it does not depend on this repository.

**Comment by DaniellMesquita** [comment]
The config.js is already on UTF-8. I'm using "Espelho Bobágico" nickname, and didn't working.

**Comment by Ecuacion** [comment]
With the 6c5c0ec09829be5ccb63d2d2ccee8090e5877c8d changes it works for me.

Did you update you bot dependecies? The bug was in the node module `node-ps-client.` Try `npm install --production`

**Comment by DaniellMesquita** [comment]
This was the trick: update dependencies with 'npm install --production'. Thanks!
You can close this issue now.
