### ISSUE TITLE
Bot's AI

### ISSUE THREAD

**Issue by Latios1** [Ecuacion/Pokemon-Showdown-Node-Bot#35]
Is it possible to improve bot's AI?(in the battles)

**Comment by Ecuacion** [comment]
Currently, the bot battle system uses an algorithm, not an artificial intelligence. It's possible to improve the algorithm but anyway it's predictable and easy to win, so it doesn't matter too much.

Probably i'll refactor the system to use an artificial intelligence or a much complicated algorithm, but it's really difficult because Pokemon has a lot of mechanics to be aware of and a lot of not-absolute situations (50-50s, hax, lures, etc). Anyway it's a good and interesting project but long-term.
