### ISSUE TITLE
Sometimes, The Pokemon uses a move on its ally.

### ISSUE THREAD

**Issue by Salamencizer** [Ecuacion/Pokemon-Showdown-Node-Bot#45]
This mostly happens in doubles and triples. The reason is unknown. I'll post replays when I see this happens. 
Anyways, Thanks for such a wonderful bot!

**Comment by Salamencizer** [comment]
Also sometimes, the bot becomes inactive: http://replay.pokemonshowdown.com/rom-tripleshackmonscup-8249
Mostly happens when the opponent has a stat raise and the bot has only one poke left.

**Comment by asanrom** [comment]
Hitting allies problem fixed by cd8a2e3e996bcb796ee2008f609f8012c36a8a42

Also, I tried to reproduce the situations where the bot goes inactive (it means that the bot sends an invalid decision), but in my case the bot never goes inactive. If your bot goes inactive in a battle and you're there, try to get the decision it is trying to send with the command `.eb this.lastSend.decision` and maybe we can figure out what's happening.

**Comment by Salamencizer** [comment]
Thanks alot

**Comment by asanrom** [comment]
Fixed by e1c56a3adaccf855415a254245d052f8656afe62

**Comment by Salamencizer** [comment]
Thanks alot!
